apiVersion: apps/v1
kind: Deployment
metadata:
  name: lumen-project
spec: 
  replicas: 2
  selector: 
    matchLabels: 
      app: lumenProjectL
  template:
    metadata:
      labels:
        app: lumenProjectL
    spec: 
      containers:
      - name: lumen-project
        image: ashraf514/lumen-app:v1
        env:
        # fetch value from the config.yaml (which contain less sensitive info)
          - name: APP_NAME
            valueFrom: 
              configMapKeyRef: 
                name: app-config
                key: APP_NAME
        # fetch value from the secret.yaml (which contain more sensitive info)
          - name: DB_PASSWORD
            valueFrom: 
              secretKeyRef:
                name: secret-vars
                key: DB_PASSWORD
          - name: LOG_CHANNEL
            value: "database"
        ports:
        - containerPort: 8001
---
apiVersion: v1
# Service for exposing the Lumen application
kind: Service
metadata:
  # service name
  name: lumen-project-service
spec:
  selector:
    # Match pods labled app=lumenProjectL in deployment.yaml
    app: lumenProjectL
  #type of service to run in the browser
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8001
    # nodePort: 32000