name: First CI
on:
  # push:
  #   branches: ["yaml-env"]
  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Say Hello
        run: echo "Hello this is the first pipeline!"
      
      - name: Run a multi-line script
        run: |
          echo "Hello this is the other step"
          echo "Test and deploy the project"
      - name: Check directory list
        run: |
          ls -l
      - name: Set and test ENV
        env: 
          APP_ENV: "Development" # non sensitive information
          DB_PASSWORD: ${{secrets.DB_PASSWORD}} # Sensitive info can't be written directly. Access it from github actions secrets.
        run: echo "The APP_ENV is $APP_ENV and the DB_PASSWORD is $DB_PASSWORD"
      - name: Create demo file
        run: |
          echo "Hello from CI/CD" > demo.txt
          echo "file created successfully"

      - name: Upload artifact Demo
        uses: actions/upload-artifact@v4
        with:
          name:
            build-artifact-demo
          path:
            .
  test:
    runs-on: ubuntu-latest
    needs: build #this will ensure first build job is executed
    steps:
      - name: Run a multi-line script
        run: |
          echo "Test Job by ${{github.actor}}"
          echo "Used to run tests via pipeline"
        #github.actor will is a context object which will return the name of the user github is logged in